import React from 'react';
import StyledComponentsRegistry from '@/components/AntdRegistry';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import '@/theme/globals.scss';

export const metadata = {
  title: 'next-antd-pc',
  description: 'Generated by create next and antd app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <StyledComponentsRegistry>
          <AuthProvider>{children}</AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
